export const refs = {
  movieContainer: document.querySelector('.js-movies-container'),
  pagination: document.querySelector('.js-paginator'),
  searchMovieInput: document.querySelector('.js-search-form__input'),
  searchForm: document.querySelector('.js-search-form'),
  backdrop: document.querySelector('.backdrop'),
  libraryButtonsBlock: document.querySelector('.js-library-buttons-block'),
  buttonLibraryWatched: document.querySelector('.js-watched'),
  buttonLibraryQueue: document.querySelector('.js-queue'),
  notificationWarning: document.querySelector('.header__warning'),
  themeToggle: document.querySelector('.themetoggle'),
  bodyEl: document.body,
  buttonCloseBackdrop: document.querySelector('.js-close-backdrop'),
  html: document.querySelector('html'),
  iconTheme: document.querySelector('.themetoggle span'),
  headerWrap: document.querySelector('.header__wrap'),
  links: document.querySelectorAll('a.header__menu-link'),
  background: document.querySelector('.header'),
  libraryNotification: document.querySelector('.library-notification'),
};
